"""Initial schema

Revision ID: 87752f434adb
Revises: 
Create Date: 2026-08-22 09:29:15.528409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87752f434adb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('synopsis', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shows_section', 'shows', ['section'], unique=False, postgresql_where=sa.text("status = 'published'"))
    op.create_index(op.f('ix_shows_slug'), 'shows', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('publish_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('show_count', sa.Integer(), nullable=True),
    sa.Column('episode_count', sa.Integer(), nullable=True),
    sa.Column('catalogue_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'season_number', name='uq_season_show_number')
    )
    op.create_index(op.f('ix_seasons_show_id'), 'seasons', ['show_id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('episode_title', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('content_group', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_episode_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_group', 'language', name='uq_content_group_language')
    )
    op.create_index(op.f('ix_episodes_content_group'), 'episodes', ['content_group'], unique=False)
    op.create_index(op.f('ix_episodes_season_id'), 'episodes', ['season_id'], unique=False)
    op.create_index(op.f('ix_episodes_show_id'), 'episodes', ['show_id'], unique=False)
    op.create_table('artwork',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=True),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('artwork_type', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(show_id IS NOT NULL AND episode_id IS NULL) OR (show_id IS NULL AND episode_id IS NOT NULL)', name='chk_artwork_target'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'artwork_type', name='uq_artwork_episode_type'),
    sa.UniqueConstraint('show_id', 'artwork_type', name='uq_artwork_show_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artwork')
    op.drop_index(op.f('ix_episodes_show_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_season_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_content_group'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_seasons_show_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_table('publish_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shows_slug'), table_name='shows')
    op.drop_index('idx_shows_section', table_name='shows', postgresql_where=sa.text("status = 'published'"))
    op.drop_table('shows')
    # ### end Alembic commands ###
